task2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

task2/objects/Home_Country__c.object
<CustomObject>
    <label>Home Country</label>
    <nameField>
        <label>Home Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

task2/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

task2/objects/Product_Details__c.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <label>Cost per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Details</relationshipLabel>
        <relationshipName>Product_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Details</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

task2/globalValueSets/Home_Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>DE</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

task2/classes/ContactProductController.cls
/**
 * Created by Yevhenii on 20.04.2019.
 */

public with sharing class ContactProductController {
	@TestVisible
	private static Contact caseContact { get; set; }

	@AuraEnabled
	public static Product_Details__c getContactProductDetailsFromCase(String caseId) {
		List<Product_Details__c> optionsList = new List<Product_Details__c>();
		initCaseContact(caseId);
		if (caseContact != null) {
			optionsList = [
					SELECT Id, Product__r.Name, Cost_per_Calendar_Month__c, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c
					FROM Product_Details__c
					WHERE Product__c = :caseContact.Product__c AND Home_Country__c = :caseContact.Home_Country__c
					LIMIT 1
			];
		}
		return !optionsList.isEmpty() ? optionsList[0] : null;
	}

	@TestVisible
	private static void initCaseContact(String caseId) {
		if (caseContact == null) {
			for (Case c : [SELECT Id, Contact.Product__c, Contact.Home_Country__c FROM Case WHERE Id = :caseId LIMIT 1]) {
				caseContact = c.Contact;
			}
		}
	}
}