task2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

task2/objects/Home_Country__c.object
<CustomObject>
    <label>Home Country</label>
    <nameField>
        <label>Home Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

task2/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

task2/objects/Product_Details__c.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <label>Cost per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Product Details</relationshipLabel>
        <relationshipName>Product_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Details</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

task2/globalValueSets/Home_Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>DE</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

task2/classes/ContactProductControllerTest.cls
/**
 * Created by Yevhenii on 22.04.2019.
 */

@IsTest
private class ContactProductControllerTest {
	@TestSetup
	static void testSetup() {
		Product__c p = new Product__c(Name = 'Standard');
		insert new Product__c[] { p };

		Product_Details__c pd = new Product_Details__c(Product__c = p.Id, Home_Country__c = 'DE', Card_Replacement_Cost__c = 10, ATM_Fee_in_other_currencies__c = 1.5, Cost_per_Calendar_Month__c = 5);
		insert new Product_Details__c[] { pd };

		Contact contact = new Contact(LastName = 'Contact1', Home_Country__c = 'DE', Product__c = p.Id);
		insert new Contact[] { contact };

		Case c = new Case(ContactId = contact.Id, Status = 'New', Origin = 'Web');
		insert new Case[] { c };
	}

	@IsTest
	static void getContactProductDetailsFromCaseTest() {
		for (Case c : [SELECT Id FROM Case LIMIT 1]) {
			Product_Details__c pd = ContactProductController.getContactProductDetailsFromCase(c.Id);
			System.assertNotEquals(null, pd);
			System.assertEquals(10, pd.Card_Replacement_Cost__c);
			System.assertEquals(5, pd.Cost_per_Calendar_Month__c);
			System.assertEquals(1.5, pd.ATM_Fee_in_other_currencies__c);
		}
	}

	@IsTest
	static void initCaseContactTest() {
		System.assertEquals(null, ContactProductController.caseContact);
		for (Case c : [SELECT Id FROM Case LIMIT 1]) {
			ContactProductController.initCaseContact(c.Id);
		}
		for (Contact c : [SELECT Id FROM Contact LIMIT 1]) {
			System.assertEquals(c.Id, ContactProductController.caseContact.Id);
		}
	}
}